// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6ZmIqN0x_K8lV2ZxpQuUCUKMPlZbBIU',
    appId: '1:902539622121:web:231e9d6fca3a1dd123a278',
    messagingSenderId: '902539622121',
    projectId: 'movie-app-95f87',
    authDomain: 'movie-app-95f87.firebaseapp.com',
    storageBucket: 'movie-app-95f87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpeq9d6bcpa3DtEC-zbp0bu3D07f6XKY',
    appId: '1:902539622121:android:6039ae15604e2e2b23a278',
    messagingSenderId: '902539622121',
    projectId: 'movie-app-95f87',
    storageBucket: 'movie-app-95f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaT8BZxrBKFQJzWG4U7MNxVP3sXZIFKek',
    appId: '1:902539622121:ios:2c666d48353ef73423a278',
    messagingSenderId: '902539622121',
    projectId: 'movie-app-95f87',
    storageBucket: 'movie-app-95f87.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaT8BZxrBKFQJzWG4U7MNxVP3sXZIFKek',
    appId: '1:902539622121:ios:2c666d48353ef73423a278',
    messagingSenderId: '902539622121',
    projectId: 'movie-app-95f87',
    storageBucket: 'movie-app-95f87.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO6ZmIqN0x_K8lV2ZxpQuUCUKMPlZbBIU',
    appId: '1:902539622121:web:6a57773ca0b81cc323a278',
    messagingSenderId: '902539622121',
    projectId: 'movie-app-95f87',
    authDomain: 'movie-app-95f87.firebaseapp.com',
    storageBucket: 'movie-app-95f87.appspot.com',
  );
}
